# Generated by Django 4.1.1 on 2022-10-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_hotel_booking_check_in_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Trip_Order",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="currency")),
                ("amount", models.CharField(max_length=255, verbose_name="amount")),
                (
                    "cart_item",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user_trip_cart",
                    ),
                ),
            ],
        ),
    ]
