# Generated by Django 4.1.1 on 2022-10-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_trip_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_trip_booking",
            name="order_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AddField(
            model_name="user_trip_booking",
            name="payment_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AddField(
            model_name="user_trip_booking",
            name="signature",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
    ]
