# Generated by Django 4.1.1 on 2022-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_trip_booking_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_trip_booking",
            name="order_id",
            field=models.CharField(max_length=255, null=True, verbose_name="order_id"),
        ),
        migrations.AlterField(
            model_name="user_trip_booking",
            name="signature",
            field=models.CharField(max_length=255, null=True, verbose_name="signature"),
        ),
    ]
