# Generated by Django 4.1.1 on 2022-10-21 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_trip_booking_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_hotel_booking",
            name="order_id",
            field=models.CharField(max_length=255, null=True, verbose_name="order_id"),
        ),
        migrations.AddField(
            model_name="user_hotel_booking",
            name="payment_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AddField(
            model_name="user_hotel_booking",
            name="signature",
            field=models.CharField(max_length=255, null=True, verbose_name="signature"),
        ),
        migrations.AlterField(
            model_name="user_hotel_cart",
            name="check_in_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 21, 21, 21, 11, 281178),
                verbose_name="check_in_date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_hotel_cart",
            name="check_in_time",
            field=models.TimeField(
                default=datetime.datetime(2022, 10, 21, 21, 21, 26, 198028),
                verbose_name="check_in_time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_hotel_cart",
            name="check_out_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 21, 21, 21, 42, 731811),
                verbose_name="check_out_date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_hotel_cart",
            name="check_out_time",
            field=models.TimeField(
                default=datetime.datetime(2022, 10, 21, 21, 21, 52, 298983),
                verbose_name="check_out_time",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="User_Hotel_Order",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("currency", models.CharField(max_length=255, verbose_name="currency")),
                ("amount", models.CharField(max_length=255, verbose_name="amount")),
                (
                    "cart_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user_hotel_cart",
                    ),
                ),
            ],
        ),
    ]
