# Generated by Django 4.1.1 on 2022-11-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_room_register_about"),
        ("users", "0007_user_guide_cart_user_guide_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_guide_booking",
            name="order_id",
            field=models.CharField(max_length=255, null=True, verbose_name="order_id"),
        ),
        migrations.AddField(
            model_name="user_guide_booking",
            name="payment_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AddField(
            model_name="user_guide_booking",
            name="signature",
            field=models.CharField(max_length=255, null=True, verbose_name="signature"),
        ),
        migrations.AlterField(
            model_name="user_guide_cart",
            name="guide",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.tourguide_reg",
            ),
        ),
        migrations.AlterField(
            model_name="user_guide_cart",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.normal_userreg",
            ),
        ),
    ]
