# Generated by Django 3.2.7 on 2021-11-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cabs_reg_driver_reg'),
        ('users', '0002_user_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user_ip', models.CharField(max_length=255, null=True, verbose_name='user_ip')),
                ('start_time', models.TimeField(max_length=255, null=True, verbose_name='start_time')),
                ('start_from', models.CharField(max_length=255, null=True, verbose_name='start_from')),
                ('end_trip', models.CharField(max_length=255, null=True, verbose_name='end_trip')),
                ('distance', models.CharField(max_length=255, null=True, verbose_name='distance')),
                ('booking_status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
                ('car_id', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.cabs_reg')),
                ('user', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.normal_userreg')),
            ],
            options={
                'verbose_name': 'Cab Booking',
                'verbose_name_plural': 'Cab Booking',
            },
        ),
    ]
