# Generated by Django 3.2.7 on 2021-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20211116_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel_booking",
            name="amount",
            field=models.CharField(
                default="0", max_length=255, null=True, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="hotel_booking",
            name="guest_no",
            field=models.CharField(
                default="0", max_length=255, null=True, verbose_name="guests"
            ),
        ),
        migrations.AlterField(
            model_name="hotel_booking",
            name="rooms",
            field=models.CharField(
                default="0", max_length=255, null=True, verbose_name="rooms"
            ),
        ),
    ]
