# Generated by Django 3.2.7 on 2021-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211116_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_booking',
            name='booking_id',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='booking_id'),
        ),
    ]
