# Generated by Django 3.2.7 on 2021-11-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20211116_1942"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel_booking",
            old_name="booking_id",
            new_name="book_id",
        ),
    ]
