# Generated by Django 3.2.7 on 2021-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211116_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_booking',
            name='book_id',
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='hotel_bookid',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='hotel_bookid'),
        ),
    ]
