# Generated by Django 3.2.7 on 2021-11-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_account_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account_details",
            options={
                "verbose_name": "Bank Details",
                "verbose_name_plural": "Bank Details",
            },
        ),
    ]
