# Generated by Django 3.2.7 on 2021-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_account_details_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab_booking',
            old_name='amount',
            new_name='amount_booking',
        ),
        migrations.RemoveField(
            model_name='hotel_booking',
            name='amount',
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='amount_booking',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='amount_booking'),
        ),
    ]
