# Generated by Django 3.2.7 on 2022-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_cab_booking_user_cab_cart_user_cab_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_guide_booking',
            name='booking_date',
            field=models.DateField(default='2021-03-09', max_length=255, null=True, verbose_name='booking_date'),
        ),
        migrations.AlterField(
            model_name='user_hotspots_bookings',
            name='booking_date',
            field=models.DateField(default='2021-03-09', max_length=255, null=True, verbose_name='booking_date'),
        ),
        migrations.AlterField(
            model_name='user_hotspots_cart',
            name='booking_date',
            field=models.DateField(default='2021-03-09', max_length=255, null=True, verbose_name='booking_date'),
        ),
    ]
