# Generated by Django 4.1.1 on 2022-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="room_register",
            name="about",
            field=models.TextField(max_length=5000, null=True, verbose_name="about"),
        ),
    ]
