# Generated by Django 4.1.1 on 2022-11-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_room_register_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg_hotel",
            name="title_image",
            field=models.ImageField(
                null=True, upload_to="hotel_images", verbose_name="title_image"
            ),
        ),
        migrations.AddField(
            model_name="room_register",
            name="title_image",
            field=models.ImageField(
                null=True, upload_to="room_images", verbose_name="title_image"
            ),
        ),
        migrations.CreateModel(
            name="RoomImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="room_images", verbose_name="image"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_constraint=False,
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.room_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="hotel_images", verbose_name="image"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        db_constraint=False,
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.reg_hotel",
                    ),
                ),
            ],
        ),
    ]
