# Generated by Django 4.1.1 on 2022-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_rename_states_room_register_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabs_reg",
            name="car_images",
            field=models.ImageField(
                null=True, upload_to="car_images", verbose_name="car_images"
            ),
        ),
        migrations.AlterField(
            model_name="cabs_reg",
            name="car_insurance",
            field=models.FileField(
                default="0",
                null=True,
                upload_to="car_insurance_files",
                verbose_name="car_insurance",
            ),
        ),
        migrations.AlterField(
            model_name="driver_reg",
            name="adhar_card",
            field=models.FileField(
                default="0",
                null=True,
                upload_to="driver_aadhar_cards",
                verbose_name="addhar_card",
            ),
        ),
        migrations.AlterField(
            model_name="driver_reg",
            name="licence_doc",
            field=models.FileField(
                default="0",
                null=True,
                upload_to="driver_licence_files",
                verbose_name="licence_doc",
            ),
        ),
        migrations.AlterField(
            model_name="driver_reg",
            name="picture",
            field=models.FileField(
                default="0",
                null=True,
                upload_to="driver_images",
                verbose_name="picture",
            ),
        ),
        migrations.RemoveField(
            model_name="tour_packages",
            name="location_ids",
        ),
        migrations.RemoveField(
            model_name="tourguide_reg",
            name="packages",
        ),
        migrations.AddField(
            model_name="tour_packages",
            name="location_ids",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="packages",
                to="clients.tour_locations",
            ),
        ),
        migrations.AddField(
            model_name="tourguide_reg",
            name="packages",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="guides", to="clients.tour_packages"
            ),
        ),
    ]
