# Generated by Django 3.2.7 on 2022-01-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('shangkai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_hotel',
            name='hotel_cat',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='shangkai_app.hotel_category'),
        ),
        migrations.AddField(
            model_name='reg_hotel',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
        migrations.AddField(
            model_name='client_token_authentication',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='driver',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.driver_reg'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
        migrations.AddField(
            model_name='account_details',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
    ]
