# Generated by Django 4.0.1 on 2022-01-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangkai_app', '0011_hotel_category_my_trips_hotspot_category_images_and_more'),
        ('clients', '0004_auto_20211117_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user_ip', models.CharField(max_length=255, null=True, verbose_name='user_ip')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='password')),
                ('user_type', models.CharField(default='0', max_length=255, null=True, verbose_name='user_type')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Clients Login',
                'verbose_name_plural': 'Clients Login',
            },
        ),
        migrations.CreateModel(
            name='Tour_locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('locations', models.CharField(max_length=255, null=True, verbose_name='locations')),
                ('location_image', models.CharField(max_length=25500, null=True, verbose_name='location_image')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Tour Locations',
                'verbose_name_plural': 'Tour Locations',
            },
        ),
        migrations.CreateModel(
            name='Tour_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('location_ids', models.CharField(max_length=255, null=True, verbose_name='location_ids')),
                ('package_amount', models.CharField(max_length=255, null=True, verbose_name='package_amount')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Tour Packages',
                'verbose_name_plural': 'Tour Packages',
            },
        ),
        migrations.RemoveField(
            model_name='cabs_reg',
            name='car_doc',
        ),
        migrations.RemoveField(
            model_name='driver_reg',
            name='driver_doc',
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='car_fee',
            field=models.CharField(max_length=255, null=True, verbose_name='car_fee'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='car_insurance',
            field=models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='car_insurance'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='car_rc',
            field=models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='car_rc'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='checkin_date',
            field=models.CharField(max_length=255, null=True, verbose_name='checkin_date'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='checkout_date',
            field=models.CharField(max_length=255, null=True, verbose_name='checkout_date'),
        ),
        migrations.AddField(
            model_name='cabs_reg',
            name='destination',
            field=models.CharField(max_length=255, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='adhar_card',
            field=models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='addhar_card'),
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='licence_doc',
            field=models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='licence_doc'),
        ),
        migrations.AddField(
            model_name='reg_hotel',
            name='hotel_cat',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='shangkai_app.hotel_category'),
        ),
        migrations.AddField(
            model_name='room_register',
            name='checkin_date',
            field=models.CharField(max_length=255, null=True, verbose_name='checkin_date'),
        ),
        migrations.AddField(
            model_name='room_register',
            name='checkout_date',
            field=models.CharField(max_length=255, null=True, verbose_name='checkout_date'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='account_no',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='account_no'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='address',
            field=models.TextField(default='0', max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='bank_branch',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='bank_branch'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='bank_name',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='bank_name'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='city',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='emergency_no',
            field=models.CharField(default='0', max_length=12, null=True, verbose_name='emergency_no'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='ifsc_code',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='ifsc_code'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='otp',
            field=models.CharField(max_length=255, null=True, verbose_name='otp'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='pin_code',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='pin_code'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='state',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='voter_id',
            field=models.CharField(default='0', max_length=255, null=True, verbose_name='voter_id'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='whatsapp_no',
            field=models.CharField(default='0', max_length=12, null=True, verbose_name='whatsapp_no'),
        ),
        migrations.AlterField(
            model_name='cabs_reg',
            name='car_images',
            field=models.CharField(max_length=25500, null=True, verbose_name='car_images'),
        ),
        migrations.AlterField(
            model_name='driver_reg',
            name='picture',
            field=models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='reg_hotel',
            name='hotel_images',
            field=models.CharField(max_length=25500, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='room_register',
            name='room_images',
            field=models.CharField(max_length=25500, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='image',
            field=models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='user_type',
            field=models.CharField(default='shangkai', max_length=255, null=True, verbose_name='user_type'),
        ),
        migrations.CreateModel(
            name='TourGuide_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('guider_name', models.CharField(max_length=255, null=True, verbose_name='guider_name')),
                ('about_guider', models.TextField(max_length=255, null=True, verbose_name='about_guider')),
                ('guider_address', models.TextField(max_length=255, null=True, verbose_name='guider_address')),
                ('guider_mobile', models.CharField(max_length=255, null=True, verbose_name='guider_mobile')),
                ('guider_email', models.CharField(max_length=255, null=True, verbose_name='guider_email')),
                ('languages', models.CharField(max_length=255, null=True, verbose_name='languages')),
                ('adhar_card', models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='addhar_card')),
                ('licence_doc', models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='licence_doc')),
                ('picture', models.FileField(default='0', max_length=255, null=True, upload_to='', verbose_name='picture')),
                ('rating', models.CharField(default='0', max_length=255, null=True, verbose_name='rating')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
                ('packages', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.tour_packages')),
                ('tour_locations', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.tour_locations')),
                ('user', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register')),
            ],
            options={
                'verbose_name': 'Tour Guide Registration',
                'verbose_name_plural': 'Tour Guide Registration',
            },
        ),
        migrations.AddField(
            model_name='tour_packages',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
        migrations.AddField(
            model_name='tour_locations',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register'),
        ),
        migrations.CreateModel(
            name='client_token_authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('is_email_verified', models.BooleanField(default=False, null=True, verbose_name='Email verification')),
                ('user_phonenumber', models.CharField(default=None, max_length=12, null=True, unique=True, verbose_name='Phone Number')),
                ('last_otp', models.IntegerField(default=None, null=True, verbose_name='Last OTP')),
                ('last_otp_time', models.DateTimeField(auto_now_add=True, verbose_name='Last OTP time')),
                ('accessToken', models.TextField(blank=True, default=None, null=True, verbose_name='Access Token')),
                ('refreshToken', models.TextField(blank=True, default=None, null=True, verbose_name='Refresh Token')),
                ('user', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.user_register')),
            ],
        ),
    ]
