# Generated by Django 4.1.1 on 2022-09-29 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About_Us",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "about_us",
                    models.TextField(
                        max_length=1000, null=True, verbose_name="about_us"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
        migrations.CreateModel(
            name="Admin_Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "message",
                    models.TextField(max_length=255, null=True, verbose_name="Message"),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="Status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin_Notification",
                "verbose_name_plural": "Admin_Notification",
            },
        ),
        migrations.CreateModel(
            name="Blog_Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Category Title"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Category",
            },
        ),
        migrations.CreateModel(
            name="Blog_Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=555, null=True, verbose_name="Post Title"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        max_length=2000, null=True, verbose_name="Post Text"
                    ),
                ),
                (
                    "feature_image",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="Feature Image"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Posts",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.CreateModel(
            name="BlogPost_Comments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user_ip",
                    models.CharField(max_length=255, null=True, verbose_name="User IP"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, null=True, verbose_name="Email"),
                ),
                (
                    "comments",
                    models.TextField(
                        max_length=2000, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post Comments",
                "verbose_name_plural": "Blog Post Comments",
            },
        ),
        migrations.CreateModel(
            name="Comments_All",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "post_id",
                    models.CharField(max_length=255, null=True, verbose_name="post_id"),
                ),
                (
                    "comments",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="comments"
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        max_length=255, null=True, verbose_name="comment_type"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comments",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Contact_Us",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, null=True, verbose_name="Email"),
                ),
                (
                    "mobile_num",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Mobile No"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        max_length=1000, null=True, verbose_name="Message"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="Status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
            },
        ),
        migrations.CreateModel(
            name="Footer_Copyright",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "footer",
                    models.TextField(max_length=1000, null=True, verbose_name="footer"),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer",
            },
        ),
        migrations.CreateModel(
            name="Hotel_Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(max_length=1000, null=True, verbose_name="title"),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Category",
                "verbose_name_plural": "Hotel Category",
            },
        ),
        migrations.CreateModel(
            name="Hotspot_Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(max_length=1000, null=True, verbose_name="title"),
                ),
                (
                    "sub_title",
                    models.CharField(
                        max_length=1000, null=True, verbose_name="sub_title"
                    ),
                ),
                (
                    "tagline",
                    models.TextField(
                        max_length=1000, null=True, verbose_name="tagline"
                    ),
                ),
                (
                    "rating",
                    models.CharField(max_length=1000, null=True, verbose_name="rating"),
                ),
                (
                    "images",
                    models.CharField(
                        default="0", max_length=25500, verbose_name="images"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotspot Category",
                "verbose_name_plural": "Hotspot Category",
            },
        ),
        migrations.CreateModel(
            name="My_Trips",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "sub_title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="sub_title"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("General", "General"),
                            ("Schools/Colleges", "Schools/Colleges"),
                            ("Research", "Research"),
                        ],
                        default="General",
                        max_length=150,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "price",
                    models.CharField(max_length=255, null=True, verbose_name="Price"),
                ),
                (
                    "offer_price",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Offer Price"
                    ),
                ),
                (
                    "special_offer",
                    models.CharField(
                        default="0",
                        max_length=255,
                        null=True,
                        verbose_name="Special Offer",
                    ),
                ),
                (
                    "deadline_date",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Deadline Date"
                    ),
                ),
                (
                    "exlusion",
                    models.TextField(
                        max_length=2550, null=True, verbose_name="Exlusion"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255, null=True, verbose_name="description"
                    ),
                ),
                (
                    "services",
                    models.TextField(
                        max_length=255, null=True, verbose_name="services"
                    ),
                ),
                (
                    "hotspots_id",
                    models.CharField(
                        max_length=255, null=True, verbose_name="hotspots"
                    ),
                ),
                (
                    "includes",
                    models.TextField(
                        max_length=255, null=True, verbose_name="includes"
                    ),
                ),
                (
                    "rules",
                    models.TextField(max_length=255, null=True, verbose_name="rules"),
                ),
                (
                    "days_no",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="days_no"
                    ),
                ),
                (
                    "start_trip",
                    models.DateField(
                        default="2021-03-09",
                        max_length=2000,
                        null=True,
                        verbose_name="start_trip",
                    ),
                ),
                (
                    "images",
                    models.CharField(
                        default="0", max_length=25500, null=True, verbose_name="images"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "My Trips",
                "verbose_name_plural": "My Trips",
            },
        ),
        migrations.CreateModel(
            name="Payment_Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, null=True, verbose_name="user_id"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=255, null=True, verbose_name="transaction_id"
                    ),
                ),
                (
                    "transaction_type_id",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="transaction_type_id"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transaction",
            },
        ),
        migrations.CreateModel(
            name="My_Trips_Days",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255, null=True, verbose_name="description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
                (
                    "my_trip",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shangkai_app.my_trips",
                    ),
                ),
            ],
            options={
                "verbose_name": "My Trips days",
                "verbose_name_plural": "My Trips Days",
            },
        ),
        migrations.CreateModel(
            name="Hot_Spots",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "sub_title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="sub_title"
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=255, null=True, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(max_length=255, null=True, verbose_name="state"),
                ),
                (
                    "pin_code",
                    models.CharField(
                        max_length=255, null=True, verbose_name="pin_code"
                    ),
                ),
                (
                    "geo_location",
                    models.CharField(
                        max_length=255, null=True, verbose_name="geo_location"
                    ),
                ),
                (
                    "amenites",
                    models.CharField(
                        max_length=255, null=True, verbose_name="amenites"
                    ),
                ),
                (
                    "history",
                    models.CharField(max_length=255, null=True, verbose_name="history"),
                ),
                (
                    "about",
                    models.TextField(max_length=2000, null=True, verbose_name="about"),
                ),
                (
                    "images",
                    models.CharField(
                        default="0", max_length=25500, verbose_name="images"
                    ),
                ),
                (
                    "entry_fee",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="entry_fee"
                    ),
                ),
                (
                    "parking_fee",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="parking_fee"
                    ),
                ),
                (
                    "rating",
                    models.CharField(max_length=2000, null=True, verbose_name="rating"),
                ),
                (
                    "tags",
                    models.TextField(max_length=2000, null=True, verbose_name="tags"),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shangkai_app.hotspot_category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotspots",
                "verbose_name_plural": "Hotspots",
            },
        ),
    ]
