# Generated by Django 4.1.1 on 2022-09-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shangkai_app", "0001_initial"),
        ("users", "0001_initial"),
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments_all",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.normal_userreg",
            ),
        ),
        migrations.AddField(
            model_name="blogpost_comments",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="shangkai_app.blog_post",
            ),
        ),
        migrations.AddField(
            model_name="blog_post",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="shangkai_app.blog_category",
            ),
        ),
        migrations.AddField(
            model_name="blog_post",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.user_register",
            ),
        ),
        migrations.AddField(
            model_name="blog_category",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.user_register",
            ),
        ),
    ]
