# Generated by Django 4.1.1 on 2022-10-02 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "shangkai_app",
            "0003_hot_spots_para1_hot_spots_para2_hot_spots_para3_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                ("datetime", models.DateTimeField(verbose_name="Starting on")),
                ("seats", models.IntegerField()),
                (
                    "payment_id",
                    models.CharField(
                        max_length=255, null=True, verbose_name="payment_id"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking",
                "verbose_name_plural": "Tracking",
            },
        ),
        migrations.AlterField(
            model_name="hot_spots",
            name="para1",
            field=models.TextField(max_length=2000, null=True, verbose_name="para1"),
        ),
        migrations.AlterField(
            model_name="hot_spots",
            name="para2",
            field=models.TextField(max_length=2000, null=True, verbose_name="para2"),
        ),
        migrations.AlterField(
            model_name="hot_spots",
            name="para3",
            field=models.TextField(max_length=2000, null=True, verbose_name="para3"),
        ),
        migrations.AlterField(
            model_name="hot_spots",
            name="title_image",
            field=models.ImageField(
                null=True, upload_to="hotspot_images", verbose_name="title_image"
            ),
        ),
    ]
