# Generated by Django 4.1.1 on 2022-10-04 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shangkai_app",
            "0004_tracking_alter_hot_spots_para1_alter_hot_spots_para2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking",
            name="booking_upto",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 4, 10, 0, 31, 262088),
                verbose_name="Booking upto",
            ),
            preserve_default=False,
        ),
    ]
