# Generated by Django 4.1.1 on 2022-10-07 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_hotel_booking_check_in_date_and_more"),
        ("shangkai_app", "0005_tracking_booking_upto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracking",
            old_name="datetime",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="tracking",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="tracking",
            name="amount",
            field=models.CharField(max_length=255, null=True, verbose_name="amount"),
        ),
        migrations.AddField(
            model_name="tracking",
            name="booked",
            field=models.IntegerField(default=0, verbose_name="booked"),
        ),
        migrations.AddField(
            model_name="tracking",
            name="booking_start",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 7, 16, 38, 8, 391436),
                verbose_name="Booking on",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracking",
            name="seats",
            field=models.IntegerField(verbose_name="seats"),
        ),
        migrations.CreateModel(
            name="Tracking_Bookings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=255, null=True, verbose_name="transaction_id"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("seats", models.IntegerField()),
                (
                    "amount",
                    models.CharField(max_length=255, null=True, verbose_name="amount"),
                ),
                (
                    "status",
                    models.CharField(
                        default="0", max_length=255, null=True, verbose_name="status"
                    ),
                ),
                (
                    "tracking",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shangkai_app.tracking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.normal_userreg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Bookings",
                "verbose_name_plural": "Tracking Bookings",
            },
        ),
    ]
