# Generated by Django 4.1.1 on 2022-10-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shangkai_app", "0006_rename_datetime_tracking_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking_bookings",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="tracking",
            name="amount2",
            field=models.CharField(max_length=255, null=True, verbose_name="amount"),
        ),
        migrations.AddField(
            model_name="tracking_bookings",
            name="order_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AddField(
            model_name="tracking_bookings",
            name="payment_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AddField(
            model_name="tracking_bookings",
            name="signature",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment_id"
            ),
        ),
        migrations.AlterField(
            model_name="hotspot_images",
            name="hotspot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotspot_images",
                to="shangkai_app.hot_spots",
            ),
        ),
    ]
