# Generated by Django 4.1.1 on 2022-10-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shangkai_app", "0008_alter_tracking_amount_alter_tracking_amount2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="my_trips_days",
            name="my_trip",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_days",
                to="shangkai_app.my_trips",
            ),
        ),
    ]
