# Generated by Django 4.1.1 on 2022-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shangkai_app", "0009_alter_my_trips_days_my_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking",
            name="student_amount",
            field=models.CharField(
                max_length=255, null=True, verbose_name="student amount a"
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="student_amount2",
            field=models.CharField(
                max_length=255, null=True, verbose_name="student amount b"
            ),
        ),
        migrations.AddField(
            model_name="tracking_order",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="is_student"),
        ),
        migrations.AlterField(
            model_name="tracking_bookings",
            name="order_id",
            field=models.CharField(max_length=255, null=True, verbose_name="order_id"),
        ),
        migrations.AlterField(
            model_name="tracking_bookings",
            name="signature",
            field=models.CharField(max_length=255, null=True, verbose_name="signature"),
        ),
    ]
