# Generated by Django 4.1.1 on 2022-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shangkai_app", "0012_coupon_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_trips",
            name="rating",
            field=models.FloatField(default=4, null=True, verbose_name="rating"),
        ),
    ]
