# Generated by Django 3.2.7 on 2022-01-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('shangkai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_all',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.normal_userreg'),
        ),
    ]
