# Generated by Django 3.2.7 on 2021-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangkai_app', '0006_auto_20211117_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_spots',
            name='amenites',
            field=models.CharField(max_length=255, null=True, verbose_name='amenites'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='geo_location',
            field=models.CharField(max_length=255, null=True, verbose_name='geo_location'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='history',
            field=models.CharField(max_length=255, null=True, verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='pin_code',
            field=models.CharField(max_length=255, null=True, verbose_name='pin_code'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='sub_title',
            field=models.CharField(max_length=255, null=True, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
