# Generated by Django 4.0.1 on 2022-01-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangkai_app', '0010_auto_20211119_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('title', models.CharField(max_length=1000, null=True, verbose_name='title')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Hotel Category',
                'verbose_name_plural': 'Hotel Category',
            },
        ),
        migrations.CreateModel(
            name='My_Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, null=True, verbose_name='sub_title')),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('Schools/Colleges', 'Schools/Colleges'), ('Research', 'Research')], default='General', max_length=150, null=True, verbose_name='Category')),
                ('price', models.CharField(max_length=255, null=True, verbose_name='price')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='description')),
                ('services', models.TextField(max_length=255, null=True, verbose_name='services')),
                ('hotspots_id', models.CharField(max_length=255, null=True, verbose_name='hotspots')),
                ('includes', models.TextField(max_length=255, null=True, verbose_name='includes')),
                ('rules', models.TextField(max_length=255, null=True, verbose_name='rules')),
                ('days_no', models.TextField(max_length=2000, null=True, verbose_name='days_no')),
                ('start_trip', models.DateField(max_length=2000, null=True, verbose_name='start_trip')),
                ('images', models.CharField(default='0', max_length=25500, null=True, verbose_name='images')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'My Trips',
                'verbose_name_plural': 'My Trips',
            },
        ),
        migrations.AddField(
            model_name='hotspot_category',
            name='images',
            field=models.CharField(default='0', max_length=25500, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='hotspot_category',
            name='rating',
            field=models.CharField(max_length=1000, null=True, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='hotspot_category',
            name='sub_title',
            field=models.CharField(max_length=1000, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='hotspot_category',
            name='tagline',
            field=models.TextField(max_length=1000, null=True, verbose_name='tagline'),
        ),
        migrations.AlterField(
            model_name='hot_spots',
            name='images',
            field=models.CharField(default='0', max_length=25500, verbose_name='images'),
        ),
        migrations.CreateModel(
            name='My_Trips_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='description')),
                ('status', models.CharField(default='0', max_length=255, null=True, verbose_name='status')),
                ('my_trip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shangkai_app.my_trips')),
            ],
            options={
                'verbose_name': 'My Trips days',
                'verbose_name_plural': 'My Trips Days',
            },
        ),
    ]
