# Generated by Django 3.2.7 on 2022-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangkai_app', '0011_hotel_category_my_trips_hotspot_category_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_trips',
            name='start_trip',
            field=models.DateField(default='2021-03-09', max_length=2000, null=True, verbose_name='start_trip'),
        ),
    ]
